baseURL = '/'
languageCode = 'fr'
title = '3IME'
theme="hugo-clarity"
paginate = 10
disqusShortname = ""

relativeURLs = true
uglyURLs = true

DefaultContentLanguage = "fr"
# [languages]
#config/languages.toml

[menu]
[[menu.main]]
  name = 'Electricité'
  url = 'categories/electricité.html'
  weight = -110
[[menu.main]]
  name = 'Electronique'
  url = 'categories/electronique.html'
  weight = -100
[[menu.main]]
  name = 'Automatisme'
  url = 'categories/automatisme.html'
  weight = -90
[[menu.main]]
  name = 'Mécanique'
  url = 'categories/mécanique.html'
  weight = -80
[[menu.main]]
  name = 'Hydraulique'
  url = 'categories/hydraulique.html'
  weight = -70
[[menu.main]]
  name = 'Pneumatique'
  url = 'categories/pneumatique.html'
  weight = -60

[taxonomies]
categorie = "categories"
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true

[params]
enableMathNotation = true

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/hint.css"]


